from __future__ import annotations

from forkfit.models import Meal


PRESET_POSTS = [
    {
        "id": "peanut-chicken-rice-bowl",
        "user_id": "preset",
        "author": "陈小敏",
        "title": "花生鸡胸肉饭碗",
        "theme": "工作日晚餐",
        "location": "上海",
        "image_urls": [
            "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=85",
        ],
        "saves": 184,
        "forks": 47,
        "description": "花生酱配西兰花和鸡胸肉，饱腹感强，适合下班快速搞定一顿。",
        "recipe": Meal(
            id="main",
            day="随便哪天",
            name="花生鸡胸肉饭碗",
            ingredients=["米饭", "鸡胸肉", "花生酱", "西兰花"],
            equipment=["灶台", "烤箱"],
            cook_time_minutes=35,
            estimated_cost=12.5,
            tags=["高蛋白", "饭碗"],
            notes="酱汁和烤箱步骤要根据口味调整。",
        ),
    },
    {
        "id": "air-fryer-salmon-potato-box",
        "user_id": "preset",
        "author": "乔恩",
        "title": "空气炸锅三文鱼土豆盒",
        "theme": "办公室午餐",
        "location": "杭州",
        "image_urls": [
            "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85",
        ],
        "saves": 231,
        "forks": 63,
        "description": "三文鱼配土豆和青豆，柠檬酸奶酱另装，到办公室再淋上去。",
        "recipe": Meal(
            id="main",
            day="午餐",
            name="空气炸锅三文鱼土豆盒",
            ingredients=["三文鱼", "土豆", "青豆", "柠檬酸奶"],
            equipment=["空气炸锅"],
            cook_time_minutes=26,
            estimated_cost=15.8,
            tags=["鱼肉", "便当"],
            notes="趁热吃最好，酸奶酱单独装。",
        ),
    },
    {
        "id": "budget-family-hotpot",
        "user_id": "preset",
        "author": "Rae Liu",
        "title": "周末番茄牛肉小火锅",
        "theme": "家庭共享餐",
        "location": "成都",
        "image_urls": [
            "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=85",
            "https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=900&q=85",
            "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85",
        ],
        "saves": 312,
        "forks": 88,
        "description": "适合三四个人一起吃的低预算小火锅，汤底浓一点会更下饭。",
        "recipe": Meal(
            id="main",
            day="周末",
            name="周末番茄牛肉小火锅",
            ingredients=["肥牛卷", "番茄汤底", "豆皮", "小白菜"],
            equipment=["炉灶"],
            cook_time_minutes=32,
            estimated_cost=18.6,
            tags=["家庭餐", "热锅"],
            notes="汤底和蔬菜可以按人数加量，适合边煮边吃。",
        ),
    },
    {
        "id": "chickpea-cauliflower-tray",
        "user_id": "preset",
        "author": "Priya",
        "title": "鹰嘴豆花椰菜烤盘",
        "theme": "素食主义",
        "location": "深圳",
        "image_urls": [
            "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=900&q=85",
        ],
        "saves": 156,
        "forks": 39,
        "description": "烤鹰嘴豆和花椰菜，淋上芝麻酱，撒点香草，简单又好吃。",
        "recipe": Meal(
            id="main",
            day="晚餐",
            name="鹰嘴豆花椰菜烤盘",
            ingredients=["鹰嘴豆", "花椰菜", "芝麻酱", "香菜"],
            equipment=["烤箱"],
            cook_time_minutes=30,
            estimated_cost=8.7,
            tags=["素食", "烤盘菜"],
            notes="配米饭或馕饼都行。",
        ),
    },
    {
        "id": "berry-yogurt-jar",
        "user_id": "preset",
        "author": "Sam Rivera",
        "title": "莓果酸奶杯",
        "theme": "早晨备餐",
        "location": "圣迭戈",
        "image_urls": [
            "https://images.unsplash.com/photo-1495214783159-3503fd1b572d?auto=format&fit=crop&w=900&q=85",
        ],
        "saves": 98,
        "forks": 21,
        "description": "不用开火的早餐杯，适合没完全醒来的早晨。",
        "recipe": Meal(
            id="main",
            day="早餐",
            name="莓果酸奶杯",
            ingredients=["希腊酸奶", "莓果", "燕麦脆", "蜂蜜"],
            equipment=[],
            cook_time_minutes=8,
            estimated_cost=5.2,
            tags=["免开火", "早餐"],
            notes="如果有坚果过敏，燕麦脆要选无坚果版本。",
        ),
    },
]
