from __future__ import annotations

from forkfit.models import Meal


PRESET_POSTS = [
    {
        "id": "peanut-chicken-rice-bowl",
        "user_id": "preset",
        "author": "Mina Chen",
        "title": "Peanut Chicken Rice Bowl",
        "theme": "weeknight dinner",
        "location": "Shanghai",
        "image_urls": [
            "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=85",
        ],
        "saves": 184,
        "forks": 47,
        "description": "A filling rice bowl with peanut sauce, broccoli, and lean chicken.",
        "recipe": Meal(
            id="main",
            day="Any day",
            name="Peanut Chicken Rice Bowl",
            ingredients=["rice", "chicken breast", "peanut sauce", "broccoli"],
            equipment=["oven", "stovetop"],
            cook_time_minutes=35,
            estimated_cost=12.5,
            tags=["high protein", "rice bowl"],
            notes="Good for meal prep, but the sauce and oven step need checking.",
        ),
    },
    {
        "id": "air-fryer-salmon-potato-box",
        "user_id": "preset",
        "author": "Jon Bell",
        "title": "Air Fryer Salmon Potato Box",
        "theme": "office lunch",
        "location": "Austin",
        "image_urls": [
            "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85",
        ],
        "saves": 231,
        "forks": 63,
        "description": "A crisp lunch box with salmon, potatoes, green beans, and lemon yogurt.",
        "recipe": Meal(
            id="main",
            day="Lunch",
            name="Air Fryer Salmon Potato Box",
            ingredients=["salmon", "potatoes", "green beans", "lemon yogurt"],
            equipment=["air fryer"],
            cook_time_minutes=26,
            estimated_cost=15.8,
            tags=["pescatarian", "lunch"],
            notes="Best eaten warm. Pack the yogurt sauce separately.",
        ),
    },
    {
        "id": "budget-family-hotpot",
        "user_id": "preset",
        "author": "Rae Liu",
        "title": "周末番茄牛肉小火锅",
        "theme": "家庭共享餐",
        "location": "成都",
        "image_urls": [
            "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=85",
            "https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=900&q=85",
            "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85",
        ],
        "saves": 312,
        "forks": 88,
        "description": "适合三四个人一起吃的低预算小火锅，汤底浓一点会更下饭。",
        "recipe": Meal(
            id="main",
            day="周末",
            name="周末番茄牛肉小火锅",
            ingredients=["肥牛卷", "番茄汤底", "豆皮", "小白菜"],
            equipment=["炉灶"],
            cook_time_minutes=32,
            estimated_cost=18.6,
            tags=["家庭餐", "热锅"],
            notes="汤底和蔬菜可以按人数加量，适合边煮边吃。",
        ),
    },
    {
        "id": "chickpea-cauliflower-tray",
        "user_id": "preset",
        "author": "Priya Shah",
        "title": "Chickpea Cauliflower Tray",
        "theme": "market vegetables",
        "location": "New York",
        "image_urls": [
            "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=900&q=85",
        ],
        "saves": 156,
        "forks": 39,
        "description": "Roasted chickpeas and cauliflower with tahini and herbs.",
        "recipe": Meal(
            id="main",
            day="Dinner",
            name="Chickpea Cauliflower Tray",
            ingredients=["chickpeas", "cauliflower", "tahini", "parsley"],
            equipment=["oven"],
            cook_time_minutes=30,
            estimated_cost=8.7,
            tags=["vegetarian", "tray bake"],
            notes="Works with rice or flatbread.",
        ),
    },
    {
        "id": "berry-yogurt-jar",
        "user_id": "preset",
        "author": "Sam Rivera",
        "title": "莓果酸奶杯",
        "theme": "早晨备餐",
        "location": "圣迭戈",
        "image_urls": [
            "https://images.unsplash.com/photo-1495214783159-3503fd1b572d?auto=format&fit=crop&w=900&q=85",
        ],
        "saves": 98,
        "forks": 21,
        "description": "不用开火的早餐杯，适合没完全醒来的早晨。",
        "recipe": Meal(
            id="main",
            day="早餐",
            name="莓果酸奶杯",
            ingredients=["希腊酸奶", "莓果", "燕麦脆", "蜂蜜"],
            equipment=[],
            cook_time_minutes=8,
            estimated_cost=5.2,
            tags=["免开火", "早餐"],
            notes="如果有坚果过敏，燕麦脆要选无坚果版本。",
        ),
    },
]
